---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: operator-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: operator