---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: operator
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/ingressgateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: operator
            port:
              number: 9443
